USE trainingTracker;
DROP TABLE IF EXISTS Users;
CREATE TABLE Users (
  nick VARCHAR(50) PRIMARY KEY,
  pass VARCHAR(50) NOT NULL ,
  email VARCHAR(50) NOT NULL UNIQUE,
  registerDate DATETIME DEFAULT CURRENT_TIMESTAMP
);
